"""empty message

Revision ID: 3de69378643a
Revises: 
Create Date: 2021-08-06 14:24:22.513446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de69378643a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('places',
    sa.Column('place_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lat', sa.Integer(), nullable=True),
    sa.Column('lng', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_table('itinerary',
    sa.Column('itinerary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itinerary_name', sa.String(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.PrimaryKeyConstraint('itinerary_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerary')
    op.drop_table('places')
    op.drop_table('tags')
    # ### end Alembic commands ###
