"""empty message

Revision ID: c09dd3272671
Revises: 
Create Date: 2021-08-16 01:22:07.240368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09dd3272671'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary',
    sa.Column('itinerary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itinerary_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('itinerary_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('places',
    sa.Column('place_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lng', sa.Numeric(), nullable=True),
    sa.Column('total', sa.Numeric(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('google_place_id', sa.String(), nullable=True),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.itinerary_id'], ),
    sa.PrimaryKeyConstraint('place_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('places')
    op.drop_table('tags')
    op.drop_table('itinerary')
    # ### end Alembic commands ###
